### ISSUE TITLE
Any way to parse video coming from links without using youtube-parser? 

### ISSUE THREAD

**Issue by jannotabamo** [nstudio/nativescript-videoplayer#105]
I want to play videos from links like `http://youtube.com/sample-video` or `http://vimeo.com/sample-video` any recommendation on how to parse it?

**Comment by bradmartin** [comment]
Nothing is built into this plugin for that use case. I believe if you're playing videos from youtube then Google (Youtube) really want you to use the youtube SDKS which have been wrapped in this plugin https://github.com/triniwiz/nativescript-youtubeplayer

**Comment by davecoffin** [comment]
Use this: https://www.npmjs.com/package/nativescript-youtube-parser

I play youtube videos using this playing in a few of my apps.
