### ISSUE TITLE
How to modify player controller layout and add buttons in angular

### ISSUE THREAD

**Issue by icipiqkm** [nstudio/nativescript-videoplayer#109]
I am a newbie. Please forgive me for the idiot problem. I want to add a full-screen button to the default controller, and I want to modify the default similarity (play button, delete forward button, adjust the size and position of the play button) Style, I am using angular. I don't understand exactly how to do it. I don't see any related options in the plugin. Hope someone can help me.

**Comment by bradmartin** [comment]
Full screen button is not implemented in the android media player by default, Google provides `exoplayer` which has been wrapped in a NS plugin. It is extended off the base of this plugin. So you could use that, as for the other buttons that you see when interacting with the videoplayer there is no way to add to those. You'd need to implement a custom layout/buttons of your own in your app and then use the public methods of the plugin (play, pause, etc.)

**Comment by icipiqkm** [comment]
@bradmartin Thank you very much. I understand what I should do
