### ISSUE TITLE
How to change source in Angular?

### ISSUE THREAD

**Issue by umair-ameen** [nstudio/nativescript-videoplayer#110]
Thank you for this amazing plugin. I am new to Nativescript I have implemented this player using Angular method which you have stated in documentation.

The issue is if i put any hard coded source of video it works perfectly but I want to get url from firebase and pass through a variable which is not working.

Also I want to know how to change the video source in Angular.

**Comment by racknoris** [comment]
@umair-ameen try to use `[src]="mySrouce"` in your html, and change `mySource`
