### ISSUE TITLE
TextureView doesn't support displaying a background drawable

### ISSUE THREAD

**Issue by tucazinul** [nstudio/nativescript-videoplayer#111]
Hello,

I'm trying to play a video on targetSdkVersion > 23 but I'm getting this error:

`ERROR Error: java.lang.UnsupportedOperationException: TextureView doesn't support displaying a background drawable`

 For targetSdkVersion <= 23 this works.

This is in Manifest.xml:

`<uses-sdk
		android:minSdkVersion="17"
		android:targetSdkVersion="__APILEVEL__"/>`

This is how I'm using it:

`<VideoPlayer
      #tutorial_video
      *ngIf="tutorialStarted"
      isUserInteractionEnabled="false"
      [src]="videoSrc"
      autoplay="true" 
      height="110%"
      controls="false"
      (finished)="setAfterVideoFinished()"
      class="tutorial"></VideoPlayer>`

Full error log:

> JS: ERROR Error: java.lang.UnsupportedOperationException: TextureView doesn't support displaying a background drawable
JS:     android.view.TextureView.setBackgroundDrawable(TextureView.java:302)
JS:     android.view.View.setBackground(View.java:18120)
JS:     org.nativescript.widgets.ViewHelper.setBackground(ViewHelper.java:534)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:970)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:954)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:946)
JS:     com.tns.gen.java.lang.Object_vendor_1_342631_ClickListenerImpl.onClick(Object_vendor_1_342631_ClickListenerImpl.java:17)
JS:     android.view.View.performClick(View.java:5609)
JS:     android.view.View$PerformClick.run(View.java:22259)
JS:     android.os.Handler.handleCallback(Handler.java:751)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.ja...
JS: ERROR CONTEXT {
JS:   "view": {
JS:     "def": {
JS:       "nodeFlags": 687882243,
JS:       "rootNodeFlags": 671088641,
JS:       "nodeMatchedQueries": 2,
JS:       "flags": 0,
JS:       "nodes": [
JS:         {
JS:           "nodeIndex": 0,
JS:           "parent": null,
JS:           "renderParent": null,
JS:           "bindingIndex": 0,
JS:           "outputIndex": 0,
JS:           "checkIndex": -1,
JS:           "flags": 671088640,
JS:           "childFlags": 0,
JS:           "directChildFlags": 0,
JS:           "childMatchedQueries": 0,
JS:           "ngContentIndex": -1,
JS:           "matchedQueries": {},
JS:           "matchedQueryIds": 0,
JS:           "references": {},
JS:           "childCount": 0,
JS:           "bindings": [],
JS:           "bindingFlags": 0,
JS:           "outputs": [],
JS:           "element": null,
JS:           "provider": null,
JS:           "text": null,
JS:           "query": {
JS:             "id": 1,
JS:             "filterId": 2,
JS:             "bindings": [
JS:               {
JS:                 "propName": "tutorialVideo",
JS:                 "bindingType": 0
JS:               }
JS:             ]
JS:           },
JS:       ...

PACKAGE.json

> "tns-android": {
      "version": "4.1.3"
    }
  "dependencies": {
    "angular/animations": "^5.2.11",
    "angular/common": "^5.2.11",
    "angular/compiler": "^5.2.11",
    "angular/core": "^5.2.11",
    "angular/forms": "^5.2.11",
    "angular/http": "^5.2.11",
    "angular/platform-browser": "^5.2.11",
    "angular/platform-browser-dynamic": "^5.2.11",
    "angular/router": "^5.2.11",
    "base-64": "^0.1.0",
    "nativescript-angular": "~5.2.0",
    "nativescript-cardview": "^2.0.5",
    "nativescript-drop-down": "^4.0.0",
    "nativescript-feedback": "^1.2.0",
    "nativescript-iqkeyboardmanager": "^1.3.0",
    "nativescript-platform-css": "^1.6.5",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-urlhandler": "^1.2.2",
    "nativescript-videoplayer": "^3.1.0",
    "nativescript-websockets": "^1.5.0",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^5.5.11",
    "tns-core-modules": "^4.1.0",
    "utf8": "^3.0.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "angular/compiler-cli": "^5.2.11",
    "ngtools/webpack": "~1.9.4",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "^0.28.11",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.6.0",
    "nativescript-dev-webpack": "^0.9.2",
    "nativescript-worker-loader": "~0.8.1",
    "node-sass": "^4.9.0",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "sass-loader": "^7.0.3",
    "tns-platform-declarations": "^3.4.1",
    "typescript": "~2.6.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-sources": "~1.1.0"
  }

**Comment by davecoffin** [comment]
What is your css for class `tutorial`?

**Comment by tucazinul** [comment]
It's just background-color: #fff;

**Comment by davecoffin** [comment]
That’s probably your problem, remove that class. A video should not have a background color.
