### ISSUE TITLE
Is it play the video with src="any youtube link" ?

### ISSUE THREAD

**Issue by JaganJonnala** [nstudio/nativescript-videoplayer#117]
I have added the code instructed by the followup page. its working fine and play the sample video with link
`https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4`

But i have changed the .mp4 file to youtube link its not at all playing loaded video player.

`<VideoPlayer row="1" id="nativeVideoPlayer" src="https://www.youtube.com/watch?v=2HQ0-G7npg8" autoplay="true" height="300"></VideoPlayer>
`
Help me out regarding this.

**Comment by davecoffin** [comment]
You can’t pass a straight YouTube url, YouTube videos contain all sorts of non video related controls. You need to parse out the actual Video url, which you can do by using an npm package called youtube-parser I think. If that’s not it comment and I’ll find the real one and get you some code when I’m at my computer.

**Comment by bradmartin** [comment]
YouTube also has a video sdk that I believe has been wrapped into a plugin of its own. That's Google's suggested way to play YouTube videos or it was a couple years ago

**Comment by JaganJonnala** [comment]
@bradmartin 
is that YouTube Sdk plugin supportable to Nativescript.?

**Comment by bradmartin** [comment]
@JaganJonnala - https://github.com/triniwiz/nativescript-youtubeplayer yes already wrapped into a cross-platform plugin

**Comment by JaganJonnala** [comment]
@bradmartin .
Thank you.
