### ISSUE TITLE
Videos not showing when using webpack (iOS)

### ISSUE THREAD

**Issue by jannotabamo** [nstudio/nativescript-videoplayer#121]
videos from using url not showing on release build.  When just running using `tns run ios` remote videos working well, but when I tried to run using `tns run ios --release --bundle --env.uglify --env.aot` video not showing. please help

**Comment by NickIliev** [comment]
@jannotabamo see [this comment](https://github.com/nstudio/nativescript-videoplayer/issues/121) for possible solution
