### ISSUE TITLE
finishedEvent fires on start and end of video

### ISSUE THREAD

**Issue by alereisan** [nstudio/nativescript-videoplayer#123]
The finishedEvent is triggered on start and end of video, while it should only be triggered at the end:

`<VideoPlayer ... (finishedEvent)="onVideoFinished($event)"></VideoPlayer>`

```
onVideoFinished(event) {
    console.log(event);   // triggered on start and end of video
}
```

**Comment by bradmartin** [comment]
Can't reproduce with the demo app. It's possible you have the event wrong event listener or it's a work flow issue.

Demo app sets the listener [here](https://github.com/nstudio/nativescript-videoplayer/blob/master/demo/app/main-view-model.ts#L26) and when the demo app starts it logs the following...

```Successfully synced application org.nativescript.videoplayer on device HT84A1A01771.
JS: Video.errorEvent executed
JS: Video.playbackStartEvent executed
JS: Video.playbackReadyEvent executed

JS: Video.finishedEvent executed
```
