### ISSUE TITLE
Not working on iOS.

### ISSUE THREAD

**Issue by delanick** [nstudio/nativescript-videoplayer#130]
Hi, my app runs well on Android but on iOS (iPhone 8) the player opens but doesn't play my video.

Please advise if you're aware of this and if I should change anything. Do you need my package.json contents?

**Comment by liam-nirvana** [comment]
Hi @delanick, I have the same problem, Are you fix it?

**Comment by delanick** [comment]
@liam-nirvana just managed to get it working on my side. For me the issue was my server is http not https, so you need to include your server in your info.plist file like this:

```
<dict>
        <key>NSExceptionDomains</key>
        <dict>
            <key>wesignit.co.za</key>
            <dict>
                <key>NSIncludesSubdomains</key>
                <true/>
                <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                <true/>
                <key>NSTemporaryExceptionMinimumTLSVersion</key>
                <string>TLSv1.1</string>
            </dict>
        </dict>
    </dict>
```

This tells iOS that bthe server security certificate is not needed and the server can bbe trusted. This worked for me, hope it works for you too!

**Comment by bradmartin** [comment]
Thanks for following up @delanick - I had never had an issue with it and the demo worked fine so I was waiting for more information before looking into it 😄 - glad you solved on your own though. That's a good learning point with iOS development and HTTPS vs HTTP urls. I remember coming across that several years ago during Cordova development and the pain it caused forced me to never forget it 😅.

**Comment by delanick** [comment]
@bradmartin no worries. Yeah I hope that was the problem and solution, it's just what worked for me. I knew iOS had issues with http urls, but didn't think video content would fall into that issue, as it's just streaming/downloading a video.
