### ISSUE TITLE
How to kill video on iOS back button

### ISSUE THREAD

**Issue by delanick** [nstudio/nativescript-videoplayer#137]
Hi @bradmartin ,

When I tap the back button on iOS, the page goes back but the video keeps playing, so you hear the audio when on other pages on the app, and when opening a new video, the original one's audio is still heard. How can I kill the video on iOS so it stops when a user clicks the back button? I know the NavigationButton on iOS can't be intercepted, so any other idea would help. Have thought of a 'Cancel/Stop' button, but for some reason the back button still appears, so don't want two buttons. Please advise :)

Please also advise how to add full screen on Android in portrait view. I have opened a ticket for this, but no response yet. I've tried fill but that doesn't work. Mute also doesn't work for muting the video. Running {N} Core CLI 5.2.0.

**Comment by bradmartin** [comment]
If the iOS NavigationButton can't be hooked into, then you'd want to use a custom navigation button to mimic the back button on iOS. You can get the official left chevron icon iOS uses on the web and then put the text with the button.

I've actually had to do this on a page in an app to prevent back navigation when certain bluetooth events were occurring. Looks and behaves well IMO.

**Comment by delanick** [comment]
@bradmartin thanks. Do you perhaps have code examples for that case of yours? Just need the XML, if it was {N} Core.

Is the official chevron in SVG format? I need it to change colour as my app does. The page in question, where I play the video, changes colour and branding to match the organisation's brand whose video it is that plays on the page.

**Comment by bradmartin** [comment]
My use was angular component for the actionbar with `ActionItem` using a `png` resource. I didn't need to change color or anything so a static white chevron worked perfectly. There are svgs available on the web but I haven't used SVGs with NS so can't speak to how that works.

**Comment by delanick** [comment]
Will give it a go, thanks. Doesn't need to be the chevron specifically, as it's just a video page. A simple close or cancel button will suffice too :)

My only issue is, when using an ActionItem, sometimes the back button appears anyway, leaving me with a back button and action item right next to each other. Any idea on how to circumvent this?

**Comment by bradmartin** [comment]
Yep: 
```xml
  <NavigationButton
    [visibility]="allowNav ? 'visible' : 'collapse'"
  ></NavigationButton>
```

set it to collapse in your template to make sure it doesn't show

**Comment by delanick** [comment]
@bradmartin I don't know how I didn't think of that. Awesome, thanks bud!!

Last question, promise: Please also advise how to add full screen on Android in portrait view. I have opened a ticket for this, but no response yet. I've tried fill but that doesn't work. Mute also doesn't work for muting the video. Running {N} Core CLI 5.2.0.

**Comment by bradmartin** [comment]
For videos on android to be full screen. I'd switch to the exoplayer plugin for videos. Think that's supported by the SDK. Sucks android doesn't provide fullscreen on video OOTB.

I've done it in the past by basically hiding a fullscreen layout offscreen and animating it on top of the entire page and then loading a video component. It looked fine and ran well but took a little time to work it in just right.

**Comment by delanick** [comment]
@bradmartin thanks! I tried exoplayer, for some reason it didn't work on Android for me, and I have no idea why. Didn't understand the errors I was getting. Thanks for your help. Will leave you alone now :)
