### ISSUE TITLE
Video don't display on ios

### ISSUE THREAD

**Issue by dieyne** [nstudio/nativescript-videoplayer#145]
The video is displayed on android. however on ios it does not display and no error reported. Here is some information about the use of the plugin in my project

Package.json

` "nativescript-videoplayer": "^4.2.1",
`

In my html component

```
<Page.actionBar>
  <ActionBar title="">
    <NavigationButton
      text="{{ 'global.back' | translate }}"
      android.systemIcon="ic_menu_back"
      (tap)="goSettings()"
    >
    </NavigationButton>
  </ActionBar>
</Page.actionBar>

<DockLayout
  class="btn-container background"
  stretchLastChild="true"
  height="100%"
>
  <StackLayout>
    <VideoPlayer
      controls="true"
      loop="true"
      dock="top"
      src="~/app/setting/static/app_demo.mp4"
      autoplay="true"
      height="100%"
    >
    </VideoPlayer>
  </StackLayout>
</DockLayout>
```

**Comment by bradmartin** [comment]
Try setting a height on the `stacklayout` since it's the parent of the video. Or remove it since you're using the `dock="top"` on the `VideoPlayer` and not the parent layout (stack in this case).

**Comment by dieyne** [comment]
i have try the two cases but it's dont work in ios .
<img width="1260" alt="Capture d’écran 2019-05-24 à 09 02 29" src="https://user-images.githubusercontent.com/33035263/58308853-f3fd2a00-7e02-11e9-8f90-96a35d21df51.png">

**Comment by bradmartin** [comment]
Very odd. I am leaning to the layout being the problem. The demo app seems to work fine still. If it's not the layout then maybe the video can't be played on iOS' media player 😕

**Comment by dieyne** [comment]
it's resolved. The mistake I made is that instead of registering the video plugin in app.module I did it in main.ts
