### ISSUE TITLE
widget is not working in popups:

### ISSUE THREAD

**Issue by aranmohyeddin** [nstudio/nativescript-videoplayer#147]
Here is my popup code:
```
<template>
  <frame id="popup">
    <page actionBarHidden="true">
      <StackLayout>
        <VideoPlayer
          class="central"
          src="~/assets/videos/color-festival.mp4"
          autoplay="true"
          controls="true"
          muted="true"
          height="500"
          fill="true"
        />
      </StackLayout>
    </page>
  </frame>
</template>

<script>
  export default {
  };
</script>

<style scoped></style>
```
and I open the modal like so:
```
      toVideo() {
        this.$showModal(nsVideo, {fullscreen: true});
      },
```
The controls don't show up, the fill attribute has no effect, I can't listen to the event(This is probably my fault but I used [this](https://github.com/nstudio/nativescript-videoplayer/issues/143#issue-432546024) method and put and alert on each of those events but none worked.
However, if copy the exact video tag you see in my code into my main frame (not in a popup) it works better, at least the controls show up.

**Comment by aranmohyeddin** [comment]
This was resolved.

**Comment by jscti** [comment]
> This was resolved.

It would have been smart to tell us how you fixed it ...

**Comment by DeepikaKochar** [comment]
I am also facing same issue, can you share your solution?

**Comment by jscti** [comment]
> I am also facing same issue, can you share your solution?

I'm now using nativescript-exoplayer

**Comment by aranmohyeddin** [comment]
@jscti I don't remember how I fixed this but I also ended up using nativescript-exoplayer
