### ISSUE TITLE
cant play local files

### ISSUE THREAD

**Issue by job111** [nstudio/nativescript-videoplayer#148]
i have a video in filesystem my path was as follow `src="file://data/data/org.nativescript.myappname/files/app/videos/storage/emulated/0/DCIM/Camera/VID_20190712_134130.mp4"` 
but it doesn't show anything, what am i missing?
In addition i tried to put a video in my app directory and tried to display it
but still facing same issue, video doesn't show at all
`<StackLayout row="1">
    <VideoPlayer  src="~app/videos/big_buck_bunny.mp4" autoplay="true" height="300"></VideoPlayer>
</StackLayout>
`

**Comment by bradmartin** [comment]
likely a webpack issue, be sure you update your copywebpackplugin to include either all `mp4` or the `videos` directory in your app.
