### ISSUE TITLE
Does this require mic permissions?

### ISSUE THREAD

**Issue by JuanDeLeon** [nstudio/nativescript-videoplayer#159]
Hello, I'm using this (great) plugin on Nativescript Vue to show a background video in my main view.

However, when I open the app on iOS (iphone 6 emulator), it is requesting microphone permissions, but I don't really have any use for the microphone, so I would prefer to not even ask for it.

Is there a way to avoid this?

**Comment by bradmartin** [comment]
Likely another plugin including the permission bc this one does not.
