### ISSUE TITLE
possibility to play youtube videos

### ISSUE THREAD

**Issue by lobo-93** [nstudio/nativescript-videoplayer#165]
i use tns with angular, and a  i want to know if is possible load youtube videos in this player and how made it, not working for the moment in angular.

**Comment by bradmartin** [comment]
Best option to satisfy how youtube/google wants you to handle youtube videos is to use their SDK for youtube, which is in this plugin: https://github.com/triniwiz/nativescript-youtubeplayer, I think you'll need an API key from youtube dev also, easy to get one if I recall
