### ISSUE TITLE
Build Plugin

### ISSUE THREAD

**Issue by pianetarosso** [nstudio/nativescript-videoplayer#168]
Hi, I'm trying to build this plugin to add some needed features for my project. 

After cloning the project, i mode in the folder `src` and run `npm run build` but this is the output with no visible folder or file created

```
> nativescript-videoplayer@4.2.1 build ..../nativescript-videoplayer/src
> npm i && tsc && npm run build.native

audited 252 packages in 1.589s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


> nativescript-videoplayer@4.2.1 build.native .../nativescript-videoplayer/src
> node scripts/build-native.js

executing 6
executing 'tns plugin build'
```

**Comment by bradmartin** [comment]
I'll take a look and update some scripts to be sure it works for your case and others :)

**Comment by bradmartin** [comment]
@pianetarosso - Plugin and demo app updated to latest NS. Please reclone your fork, and `cd src && npm run demo.android` and it'll build the plugin and start the demo app, then you can modify the src and it should update and run in the demo. Once your changes are working and you'd like to propose a PR feel free to do so 👍

**Comment by TishoTM** [comment]
I am trying to build the plugin as well but getting the errors
```
videoplayer.android.ts(217,17): error TS2339: Property 'setPlaybackParams' does not exist on type 'MediaPlayer'.
videoplayer.android.ts(218,19): error TS2339: Property 'getPlaybackParams' does not exist on type 'MediaPlayer'.
```
I am running node v12.22.1, Nativescript 8.1.1

Any suggestions?
