### ISSUE TITLE
Online Videos wont play On Android 10 - MIUI 12 

### ISSUE THREAD

**Issue by szhatef** [nstudio/nativescript-videoplayer#176]
while I can play local files easily, I can't play some online files on my device. ( Android 10, MIUI 12 )

I even tried this:  [playground](https://play.nativescript.org/?template=play-vue&id=r2qFXm&v=215 ) 

[ this video ](http://techslides.com/demos/sample-videos/small.mp4). 
on Android 10 won't work 
on Android 6 : works!

[this video](https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4): 
on Android 10 works!
on Android 6 : works!

**Comment by bradmartin** [comment]
Possibly a security config is needed for your application. You can allow all HTTP traffic or set some configuration for network access per URLs.

**Comment by szhatef** [comment]
seems right, could you help me out to implant such confings?

**Comment by bradmartin** [comment]
I believe this https://stackoverflow.com/a/51902630 will get you going in the right direction 👍  if you get stuck, let me know.
