### ISSUE TITLE
Uncaught Error: Cannot find module 'nativescript-angular/element-registry

### ISSUE THREAD

**Issue by javatutorials2016** [nstudio/nativescript-videoplayer#178]
Experience the below error. Please suggest.

(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Uncaught Error: Cannot find module 'nativescript-angular/element-registry'
at
ZoneAwareError(file: node_modules/@nativescript/zone-js/zone-nativescript.js:1298:0)

"dependencies": {
    "@angular/animations": "^10.1.5",
    "@angular/common": "~10.0.9",
    "@angular/compiler": "~10.0.9",
    "@angular/core": "~10.0.9",
    "@angular/forms": "~10.0.9",
    "@angular/localize": "~10.0.9",
    "@angular/platform-browser": "~10.0.9",
    "@angular/platform-browser-dynamic": "~10.0.9",
    "@angular/router": "~10.0.9",
    "@angular/service-worker": "~10.0.9",
    "@nativescript/angular": "~10.1.0",
    "@nativescript/camera": "^5.0.2",
    "@nativescript/core": "~7.0.0",
    "@nativescript/theme": "~2.5.0",
    "@ng-bootstrap/ng-bootstrap": "^7.0.0",
    "@schoolsquirrel/letter-avatar": "^1.0.0",
    "@stomp/ng2-stompjs": "^7.2.0",
    "@types/node-rsa": "^1.0.0",
    "@types/socket.io-client": "^1.4.33",
    "aes-js": "^3.1.2",
    "angularx-social-login": "^3.2.1",
    "bootstrap": "^4.5.0",
    "constants": "0.0.2",
    "core-js": "^3.6.5",
    "cryptico": "^1.0.2",
    "crypto": "^1.0.1",
    "crypto-module": "^1.3.19",
    "event-source-polyfill": "^1.0.16",
    "idb": "^5.0.4",
    "mediasoup-client": "^3.6.12",
    "moment": "^2.27.0",
    "nativescript-oauth2": "^3.0.1",
    "nativescript-photoviewer": "^2.1.5",
    "nativescript-rsa": "^1.0.1-beta.2",
    "nativescript-secure-storage": "^2.6.2",
    "nativescript-ui-listview": "^9.0.2",
    "nativescript-videoplayer": "^5.0.1",

  }

**Comment by javatutorials2016** [comment]
component.tns.ts: 

import {registerElement} from "nativescript-angular/element-registry";
import { Video } from 'nativescript-videoplayer';
registerElement("VideoPlayer", () => Video);

Also tried below import same error
import { registerElement } from "@nativescript/angular/element-registry";

**Comment by bradmartin** [comment]
you have `@nativescript/angular` dep

So it should be 
```ts
import { registerElement } from "@nativescript/angular";
```

**Comment by javatutorials2016** [comment]
Thanks for the suggestions. it helped and able to play video
