### ISSUE TITLE
Question: Playing Video on Viewport and More

### ISSUE THREAD

**Issue by HakobiDev** [nstudio/nativescript-videoplayer#181]
I already done this with Ionic using intersection observer but for some reason I migrate my app to hybrid native for faster loading and smoothness of native components.

I just wonder if this is can be done or anyone can tried this logic.

Additional I saw it is purely native media player is there way to customize it using api of this plugin..

Thanks...

**Comment by HakobiDev** [comment]
I just wonder if this working Nativescript Vue

**Comment by bradmartin** [comment]
You are correct that the video player is the native video player for android and iOS. I'm not sure what exactly your title means by "Viewport"? Do you mean to fill the viewport (the entire screen, like fullscreen)? 

The plugin will and does work with NS-Vue, you'll need to register the view component, this should be mentioned on the NS-Vue docs (similar to Angular https://github.com/nstudio/nativescript-videoplayer#angular-nativescript-usage).

If there is some functionality you need that the plugin does not expose, you can use the APIs of the native controls https://github.com/nstudio/nativescript-videoplayer#platform-controls-used. Happy to help answer questions with how to do things if you get stuck.

**Comment by HakobiDev** [comment]
@bradmartin sorry to interrupt you maybe I mistaken giving a tittle "Viewport" since the Nativescript itself not relying to DOM,

for exact representation what I mean like Twitter or Facebook, when you scroll and the video appeared to screen with 80% visibility the trigger play() will run and if the video have 10% visibility it will trigger pause().

Additional: I used VideoJS Lib for web version that support dynamic IDs that I can call through the logic using that scenario.

Thanks and this my first time to exploring Nativescript and creating an use case for Group.

**Comment by bradmartin** [comment]
So you want to play the video when it's visible at a certain point on the device screen? I am familiar with this on Instagram, but I've never tried implementing this myself. 

Depending on your layout, if you have a scrollview, you could prob use the scrollview scroll events and detect if the video is somewhere on the screen. If you're in a listview, you could do similar. I'm just not sure on the approach I'd take as I've never done this myself.

However, if it's possible to do natively in android/ios and you've seen it (which I can confirm I've seen on instagram) it is possible to do in NS. It's just a matter of the implementation.

**Comment by HakobiDev** [comment]
Thanks for the patient. and have a good day it seems you give me a HINT as I far I see on 
Alexander Ziskind YT page for detecting scroll events.. 

@bradmartin we will close this..  Big Thanks
