### ISSUE TITLE
Unable to play remote videos that are streamed from a DB (from urls)

### ISSUE THREAD

**Issue by woodzza** [nstudio/nativescript-videoplayer#202]
I have a strange issue which I can not resolve; no doubt am missing something simple. I have checked MIMETYPES on the server and just can not see why these urls dont all play. I am streaming the VIDEO out from a DB; and in these cases they will not play using the plugin.

https://tasks.tch.co.za/testthefile.mp4 (DOES NOT WORK)
https://tasks.tch.co.za/_imsa/testmp4a.asp (DOES NOT WORK)
https://tasks.tch.co.za/_imsa/stream1.mp4 (DOES WORK)

I suspect the issue is server side but if anyone can help point me in the right direction I would greatly appreciate it.

**Comment by MayoudP** [comment]
Did you managed to fixe the error ? Trying to play remote url as well, but doesn't work, getting an infinite loader on the player...

**Comment by woodzza** [comment]
Hi there,

I did manage to come right. What I ended up doing on the server was just saving the MP4 to the server hard drive and linking to that rather than directly streaming from the DB.

Regards, Andrew
0813132204

**Comment by franconeilglovasa** [comment]
Hi!

How did you manage to play it? Video wont play on direct mp4 link:

```
<VideoPlayer
src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
autoplay="false"
height="300">
</VideoPlayer>
```

**Comment by Cateye82** [comment]
I have the feeling that it is related with newer xcode versions. 15.2 worked fine and I had it parallel on macOS 14.5.
Now I installed 15.0 and I am not able to use 15.2 any more (not compatible). In my case it works fine in the simulator, but as far as I upload it to testflight, it won't. Is it the same with yours? I see I am a little late to the party. Maybe you have some information on how you solved it.

**Comment by woodzza** [comment]
> I have the feeling that it is related with newer xcode versions. 15.2 worked fine and I had it parallel on macOS 14.5. Now I installed 15.0 and I am not able to use 15.2 any more (not compatible). In my case it works fine in the simulator, but as far as I upload it to testflight, it won't. Is it the same with yours? I see I am a little late to the party. Maybe you have some information on how you solved it.

I changed the logic on my side to rather save the file to a cached folder and referenced that rather than a script that retrieved it and passed it to the client. Also check that you are using https:// as opposed to http://
