### ISSUE TITLE
Angular @ViewChild(Video) not working.

### ISSUE THREAD

**Issue by RobertGardner** [nstudio/nativescript-videoplayer#77]
In an Angular Nativescript project, when I use @ViewChild to access the video component, it isn't found. I can work around it, but thought there might be something strange with the implementation.

This is my code:
In x.html:
<VideoPlayer [src]="video.videoUrl" autoplay="true" height="300"></VideoPlayer>
In x.ts:
@ViewChild(Video) private vPlayer: Video;

When I try to access vPlayer I get an error that it is undefined.

The workaround:
In x.html:
<VideoPlayer #vPlayer [src]="video.videoUrl" autoplay="true" height="300"></VideoPlayer>
In x.ts:
@ViewChild("vPlayer") private vPlayer: ElementRef;

Now I have to access the player as vPlayer.nativeElement, but it works.

**Comment by bradmartin** [comment]
@bnussey - you use angular, anything wrong here?

**Comment by bnussey** [comment]
Hey @bradmartin I actually do the workaround in my project so there might be an issue if someone wants to do it the first way he's discussed. I've never tried it.

**Comment by RobertGardner** [comment]
For what it's worth, this works correctly with the Telerik Nativescript UI RadSideDrawerComponent.

**Comment by RobertGardner** [comment]
I believe the problem here is that for this to work, you have to "import" the Video component in the @NgModule that uses it. However, this isn't possible because there is no VideoModule. I think you need to declare an NgModule for the Video component and export it.

I played around with doing this, but it looks like there's no @Component declaration for Video, so I couldn't. It'd probably be easy to do all this, but it's beyond what I have time for right now.

**Comment by RobertGardner** [comment]
An update:
I tried adding the angular files for a Component and a Module, like one would expect when using a component in Angular. It didn't work, but that may be because I'm not building and deploying the component correctly.

I tried the following, which works for components I create in my own project:
Create 'angular' folder in nativescript-videoplayer and add these three files:
videoplayer.component.ts:
import { Component } from "@angular/core";

@Component({
  selector: "VideoPlayer",
  template: ""
})
export class VideoPlayerComponent {
}

videoplayer.module.ts:
import { NgModule } from "@angular/core";
import { VideoPlayerComponent } from "./videoplayer.component";

@NgModule({
  imports: [
  ],
  declarations: [
    VideoPlayerComponent
  ]
})
export class VideoPlayerModule {
}

index.d.ts:
export * from "./videoplayer.component";
export * from "./videoplayer.module";

Then in my component that uses this, I have the following:
@ViewChild(VideoPlayerComponent) private vPlayer: ElementRef;

**Comment by bradmartin** [comment]
Don't you need to import the decorators from angular for the ngmodule and
component since you use them in the code?

**Comment by RobertGardner** [comment]
Yes. Sorry, I edited my post a couple of times as I realized I'd forgotten to add details. The final version of the post shows the imports. :-)  

My module for the component that uses the video player has `VideoPlayerModule` in its NgModule imports list (this registers the `VideoPlayerComponent` with Angular). The component itself uses `import { VideoPlayerComponent } from "nativescript-videoplayer/angular";` to import the component definition so TypeScript will recognize it.

**Comment by bnussey** [comment]
Did you want to do a PR for this?

**Comment by RobertGardner** [comment]
Sure, I'll do that. It'll be a couple of days before I can get to it. I'll include the Module and Component plus a sample component that consumes it so you can make sure it works.

**Comment by bnussey** [comment]
Thanks @RobertGardner quick question -- is this consistent with how other plugins have done it?

**Comment by RobertGardner** [comment]
I'm not extremely familiar with other plugins. The only other plugin I use that exposes Angular components is Telerik's UI for NativeScript. It uses the pattern I've done here (with the Component and Module in an `angular` subdirectory), so I think it's a reasonable pattern to follow. If someone knows a more common pattern, hopefully they'll let me know!

**Comment by RobertGardner** [comment]
Yes, those both follow the pattern of putting the angular items and module in an 'angular' folder. So that seems to be the way to go. 

These two examples are both Directives while yours is a Component, but otherwise it's the same. I noticed that these both also put their Directives in the NgModule's 'exports' section, which I didn't do. I'll have to try that.

**Comment by rugdealer** [comment]
Just spent some time on this and figured it out.


**view**
```
        <VideoPlayer
                    #video_player
                    [src]="src"
                    autoplay="true"
                    height="300"></VideoPlayer>
```

**component**
```
@ViewChild("video_player") videoPlayer: ElementRef;

//In some method
this.videoPlayer.nativeElement.getCurrentTime()
```

I was confused when my app was crashing to do `this.videoPlayer.getCurrentTime()` throwing an undefined `this.videoPlayer.getCurrentTime` when doing exactly what @RobertGardner originally tried.

`@ViewChild(Video) videoPlayer: Video;`

I decided to check what "videoPlayer" was and tried a `console.dir(this.videoPlayer)` which gave me the typical` [object Object]`

What really helped figure it out was doing simply:

```
for(let prop in this.videoPlayer){
  if(this.videoPlayer.hasOwnProperty(prop)){
    console.dir(prop)
  }
}
```

This printed out "nativeElement" which I then checked what properties it had, and was glad to find all the api's defined on the documentation. Cheers.

**Comment by bradmartin** [comment]
@RobertGardner @rugdealer - one of you want to get a PR going to make this work better for angular per the discussion above?

**Comment by rugdealer** [comment]
@bradmartin Yeah, I'll take a look at it. Would be nice to get the "Video" type and avoiding the use of nativeElement.
