### ISSUE TITLE
Cannot play video with android API level 21

### ISSUE THREAD

**Issue by TuanNA58** [nstudio/nativescript-videoplayer#81]
HI Brad,

Thanks for your great plugin.

There is a issue with Android API level 21 (Lollipop 5.0). Video can not play with that android version

![screenshot_1501108360](https://user-images.githubusercontent.com/17693275/28646654-b5ea5a88-7217-11e7-8631-625a68125aee.png)

I've tested with Android Kitkat and It worked great

Please help me check it!

Thank you so much

**Comment by bradmartin** [comment]
Is it the videos from the demo? They work for me in the demo with Android
7.0 and emulators running all versions. Do any of the events work in the
demo for you?
