### ISSUE TITLE
Crash ontap

### ISSUE THREAD

**Issue by SamuelReeder** [nstudio/nativescript-videoplayer#89]
This was a hard one to catch as I dont usually sit and let the video play out. I have noticed that if you leave a video playing for a while and then try to tap it to open up the controls, the app will crash with the following error.

`System.err: com.tns.NativeScriptException:
System.err: Calling js method onTouch failed
System.err:
System.err: Error: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?`

this is follow by a bunch of runtime errors but this bit is the important part.

Any ideas on how to fix this?

**Comment by bradmartin** [comment]
Never debugged this one before. Did you figure anything out @SamuelReeder?
