### ISSUE TITLE
Crash after minimizing fullscreen video

### ISSUE THREAD

**Issue by sfaessler** [nstudio/nativescript-videoplayer#92]
Hi, we use your plugin in an app and have the problem that the video crashes after running in full screen mode and you want to minimize it again. Unfortunately, the error log does not show anything helpful either. Have you ever had this problem before and can you help?

Tested on the current iOS with different devices (6s, 7,8, X).

Thanks in advance!

Regards,
Sven

**Comment by surdu** [comment]
... how did you get the video in fullscreen ? I bet a lot of people [here](https://github.com/nstudio/nativescript-videoplayer/issues/14) would like to know 😝

**Comment by bradmartin** [comment]
iOS handles fullscreen with its default controls @surdu, Android not so much sadly. However, I just ran the demo app and have not seen it crash after minimizing. I'm pushing a fairly big update so it's possible I've corrected the issue without knowing it, so once `4.0.0` is out you can update and try it out. This will have a new `debug` prop on the `Video` instance that when set to `true` will output a lot of console.logs from the video src files to help debug issues like this.

**Comment by Omi231** [comment]
@sfaessler can you share your how yo u implemented fullscreen?
