### ISSUE TITLE
Fails to find TypeScript typing info ("Cannot find namespace 'android'")

### ISSUE THREAD

**Issue by yonghongren** [nstudio/nativescript-videoplayer#96]
Building with nativescript-video-player fails because it couldn't find TNS typing info:

```
ERROR in node_modules/nativescript-videoplayer/videoplayer.d.ts(62,12): error TS2503: Cannot find namespace 'android'.
node_modules/nativescript-videoplayer/videoplayer.d.ts(63,8): error TS2304: Cannot find name 'UIView'.
node_modules/nativescript-videoplayer/videoplayer.d.ts(1,22): error TS6053: File '/home/ren/views/yafei/nsclient/node_modules/nativescript-videoplayer/node_modules/tns-platform-declarations/android.d.ts' not found.
node_modules/nativescript-videoplayer/videoplayer.d.ts(2,22): error TS6053: File '/home/ren/views/yafei/nsclient/node_modules/nativescript-videoplayer/node_modules/tns-platform-declarations/ios.d.ts' not found.
```

I can get it to build by changing the 'reference path' in videoplayer.d.ts to:
```
/// <reference path="../../node_modules/tns-platform-declarations/android.d.ts" />
/// <reference path="../../node_modules/tns-platform-declarations/ios.d.ts" />
```
The plugin works great once it's built, but I am curious whether my setup is flawed or something as I suspect it's intended to be plug-and-play.

**Comment by edwinabt** [comment]
I am experiencing the same problem...

**Comment by bradmartin** [comment]
I've just tried a new app and didn't run into this problem. I assume your apps are using TS.

Can you check your `tsconfig.json` to make sure it's similar to the snippet below, mainly curious if making sure `node_modules` in the `exclude` option will fix your build issue.

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "lib": [
            "es6",
            "dom"
        ],
        "baseUrl": ".",
        "paths": {
            "*": [
                "./node_modules/tns-core-modules/*",
                "./node_modules/*"
            ]
        }
    },
    "exclude": [
        "node_modules",
        "platforms"
    ]
}
```

**Comment by edwinabt** [comment]
@bradmartin I am using TS. I have that exact `tsconfig.json` file you posted.  See the image attached. 
![image](https://user-images.githubusercontent.com/9532300/39576191-57e8f018-4eab-11e8-9041-e813983f0086.png)

The way I "fixed it" was to add in the `tsconfig.json`, the `skipLibCheck: true` flag, so it ignores the error and builds. Also that helps to focus my computer resources in my code and not debug libraries I get from NPM.
![image](https://user-images.githubusercontent.com/9532300/39576440-1cd021da-4eac-11e8-91c5-7b8b1749bb59.png)

**Comment by bradmartin** [comment]
That is definitely something you want to do :) I thought that was a default
myself, that helps performance a ton. Thanks for replying :)

**Comment by Burgov** [comment]
thank you for sharing @edwinabt!

**Comment by bradmartin** [comment]
4.0.3 published to help with this.
