### ISSUE TITLE
Should the events be firing when using native controls?

### ISSUE THREAD

**Issue by bengallienne** [nstudio/nativescript-videoplayer#97]
Hi,

Great plugin. We are using it in a nativescript-vue project, and it seems that the only event that actually fires (on iOS, we are still getting this up and running on Android) is the playbackReady event. The others only seem to fire if you call their respective api methods directly. We need to detect when the user scrubs, pauses or plays using the native controls. Should we expect these events to be firing, or is that not the intended behaviour?

Thanks!

**Comment by bradmartin** [comment]
Think it was just an oversight, lack of time to getting implemented. I'd have to review iOS again to get the events emitting with the media controls. Not something I have planned right now, so a PR would be much appreciated if you have any time/desire to help with that.

On android I think I have most of the events wired up, if you find something lacking, let me know as I'm more familiar with the android API and can help you get that working much quicker.

Thanks 😄

**Comment by bengallienne** [comment]
Ok that's interesting to know you are ok with that, we'll have a look! Would you be against us changing the status observer in the PR to be more wide ranging in what it observes to try and catch these events?

**Comment by bradmartin** [comment]
Not at all, any improvements are welcome 🎉 just keep me posted if you have something breaking in mind so we can at least discuss it and possibly mitigate any major bumps, unless it's completely unavoidable.

**Comment by bengallienne** [comment]
will do, thanks!
