### ISSUE TITLE
Video not playing in Android which was taken from iOS vice versa

### ISSUE THREAD

**Issue by madhanagopalgit** [nstudio/nativescript-videoplayer#99]
Hi,
I am using Nativescript-Videoreorder & Nativescript-Videoplayer
"nativescript-videoplayer": "^3.1.0",
"nativescript-videorecorder": "^3.0.0-alpha.6",

Video which was recorded using Android is not Playing in iOS. Same thing happens when we record video in iOS it is not playing in Android. In both the scenario videos are playing in same OS.

Please help us to resolve this issue.

Regards
Madhan

**Comment by bradmartin** [comment]
What are the video formats? Knowing that, we can check if the native media players support the file extension. If it does, then we can check the player to add the code necessary to support it.

**Comment by bradmartin** [comment]
Closing as this is more OS and recording related and not playback.

See [this SO post](https://stackoverflow.com/a/23628039/1893557). Changing the encoding of the recording if you are recording inside your app would be a quick fix, or modifying your backend to handle the change.
